@namespace
class SpriteKind:
    allie = SpriteKind.create()
def quest9():
    adventure.add_to_textlog("You got tackled and pinned down by pirates.")
    pause(100)
    adventure.add_to_textlog("They decided to make you the cabin boy.")
    pause(100)
    adventure.add_to_textlog("Cabin boy jobs include:    moping the decks,  following orders,  untangling the ropes, & cleaning the ship.")
    pause(1500)
    adventure.add_to_textlog("press (A) to get to work.   Press (B) to try and annoy them into letting you go.             press (arrow key) to jump over the side of the boat.")
    pause(100)
    
    def on_pause_until():
        pass
    pause_until(on_pause_until)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you get to work immediately.")
        questsplit1b()
    elif controller.B.is_pressed():
        adventure.add_to_textlog("you start singing the wellerman:")
        adventure.add_to_textlog("there once was a ship that put to sea, the name of the ship was the billy o' tea. The winds blew hard and bowed her down and blow my billy boys, blow. Soon may the wellerman come to bring us sugar and tea and rum one day when the tugging is done will take our leave and go. She'd  not been to weeks from shore when down on her a right whale bore. The captin called all hands and swore he'd take that whale in tow.  Soon may the wellerman come to bring us sugar and tea and rum one day when the tugging is done we'll take our leave and go. Da-da-da-da-da Da-da-da-da-da-da-da Da-da-da-da-da-da-da-da-da-da-da. Before the boat had hit the water The whale's tail came up and caught her All hands to the side, harpooned and fought her When she dived down low. soon may the wellerman come to bring us sugar and tea and rum one day when the tugging is done we'll take our leave and go. No line was cut, no whale was freed The captain's mind was not of greed And he belonged to the Whaleman's creed She took that ship in tow. Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tugging is done We'll take our leave and go. Da-da-da-da-da Da-da-da-da-da-da-da Da-da-da-da-da-da-da-da-da-da-da. For forty days or even more The line went slack then tight once more All boats were lost, there were only four But still that whale did go. Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tugging is done We'll take our leave and go. As far as I've heard, the fight's still on The line's not cut, and the whale's not gone The Wellerman makes his regular call To encourage the captain, crew and all. Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tugging is done We'll take our leave and go. Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tugging is done We'll take our leave and go.")
        pause(1000)
        adventure.add_to_textlog("The pirates told you that they changed their minds and decided that you would sing sea shantys for them")
        pause(100)
        questsplit1()
    else:
        adventure.add_to_textlog("you jumped over the side of the ship.")
        adventure.add_to_textlog("It was wet.")
        adventure.add_to_textlog("the pirates pulled you aboard and forced you to work at sword point.")
        questsplit1b()
def quest3():
    music.play(music.create_song(assets.song("""
            quest_from_the_king
        """)),
        music.PlaybackMode.IN_BACKGROUND)
    scene.set_background_color(15)
    adventure.add_to_textlog("you are traveling")
    adventure.add_image_to_text_log(assets.image("""
        wounded
    """))
    adventure.add_to_textlog("you enter a forest")
    adventure.add_to_textlog("Press (A) to keep going")
    adventure.add_to_textlog("Press (B) to run away")
    
    def on_pause_until2():
        pass
    pause_until(on_pause_until2)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you keep going")
        adventure.add_image_to_text_log(img("""
            .55................................................55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55eeeeeeeeeeeeeeeeeeeee111111eeeeeeeeeeeeeeeeeeeee55.
                        .55dddddddddddddddddddd15555554dddddddddddddddddddd55.
                        .55dddddddddddddddddddd155ee554dddddddddddddddddddd55.
                        .55dddddddddddddddddddd15eeee54dddddddddddddddddddd55.
                        5555555555555555555555515eeee5455555555555555555555555
                        11111111111111111111111155ee55411111111111111111111111
                        55555555555555555555555155ee55455555555555555555555555
                        55555555555555555555555155ee55455555555555555555555555
                        444444444444444444444441555555444444444444444444444444
                        .55ddddddddddddddddddddd444444ddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        .55dddddddddddddddddddddddddddddddddddddddddddddddd55.
                        111111111111111111111111111111111111111111111111111111
                        555555555555555555555555555555555555555555555555555555
                        555555555555555555555555555555555555555555555555555555
        """))
        adventure.add_to_textlog("you got coins!")
        adventure.change_score_override(adventure.Currency.COINS, 5)
        quest4()
    else:
        adventure.add_image_to_text_log(assets.image("""
            dagon
        """))
        adventure.add_to_textlog("you were eaten by a dragon...")
        info.change_life_by(-3)
def quest4():
    adventure.add_to_textlog("you exit the forest.")
    adventure.add_to_textlog("you see a castle...")
    adventure.add_image_to_text_log(img("""
        ..........................................................................................
                ..........................................................................................
                ..........................................................................................
                ..........................................................................................
                .......................................d..................................................
                ......................................dcf.................................................
                ......................................daf.................................................
                .....................................dbabf................................................
                .....................................dacccf...............................................
                ....................................dbacccf...............................................
                ....................................dabccbbf..............................................
                ....................................dabcccbf..............................................
                ...................................dabccccbbf.............................................
                ...................................dacbcbcccf.............................................
                ..................................dcbbbcbbbccf.....dbbbb.baaa..baaa.......................
                ..................................dacccccccccff....daccb.accc.daccf.......................
                .................................dcaccbbbbccccf....dacbb.accc.dacbf.......................
                .................................dabbbbbbbbbbbff...dbccb.abbb.dbbcf.......................
                ................................dbbcccccccccbbbf...daccbbbccbbdcccf.......................
                ................................ffcccccccccccfff....acbbcccbbccbcbf.......................
                ..................................ffffffffffff......accbcccccccccbf.......................
                ..................................ccbbbbbbcccc......accbbbbbbcccccf.......................
                ..................................abcbbccbbbbb.......bbbcbbbccbbbf........................
                ..................................bbcbbbbbbbbb........baccccffcbf.........................
                ..................................abbbcccbbbbb........dacccffffff.........................
                ..................................bccccccccccb........dacbbbbbccf.........................
                ...................................cccccccccf.........dbbbbccbbcf.........................
                ...................................abcccccccf.fffffff.cabbbbccccf.........................
                ...................................abccbbbbbffaaaadbff6abccbbbbcf.........................
                ................daabb..bbbbb..bbbf.bbccbbbbcfaadbbbbb66abbbbbbbcf.........................
                ................dbbbb..bbbbb..bbbf.abbbbbbbcfbbcbbcbbccabbbccbbcf.........................
                ................dccccbfcccccbbcccf.abbbcbccbfbbbbbcbbbfabbbccbbcf.........................
                ................dbbbbbbbbbbbbbbcbf.abbccbbbcfbbcccbbbbfbbbbbbbbcf.........................
                ................dccbbbbcbcccbbccbf.abbbbbbbcfcccccccbbfabbbbccccf.........................
                .................baccccccccccccccf.bbcbbbbbcfcc...cccffabcbbccccf.........................
                ..................abbbbbbcbbbbbbcf.abccbbbbcfc.....ccffabbbbbbccf.........................
                ..................cabccbbccbbbccf..abccbccbcf.......cffabbbbbbccf.........................
                ...................cabbbbbbbbcff...abccbbbbcf.......cffacbbcbbccf.........................
                ....................ccccccccfff....abccbbbbcf.......cffacbbcbbccf.........................
                ....................cccccccccccddbbbbccbbbbcf.......cffacbbbbbccf.........................
                ....................dabbbbbbbbcbbccccccbbbbbff.....ccfbacbbbbbccf.........................
                ....................dbbbccbbbbcbcccccccccbbccbf...cccfaccccccbccf.........................
                ....................dacbccbbcccbcce4ccbbbbbbccbfccccaacbbbcbbbccf.........................
                ....................dacbbbbbcbbbcc4cccbbccbbcbbbbccccbcbbbbcbcccf.........................
                ....................dabbbbcbbbbbbccbbbcbccbbcbbbbcbbbcbbccccccccf.........................
                ....................dbbbbbccbbccbccbbbcbbbbbcbbcccbccccbccbbbbccf.........................
                ....................daccbbbfaaccbbbbbbbbbbbbbbbbccbbbcfaaabbcbccf.........................
                ....................dabbbbfcccabbbbbbbccbbcccbbbbbbbbfcccabccbccf.........................
                ....................dabcbfcccccabcccbbccbbccbbbcccbbfcccccaccbccf.........................
                ....................dabcbfccbccabbcbbbbbbbbbbbbcccbcfccbccabbbccf.........................
                ....................dbbcbfcccccabbbbbbbbffcaabbbbbbcfcccccaccbccf.........................
                ....................dabbbfcccccabbcccccfcccccaabbbbbfcccccabbcccf.........................
                ....................dabcbfcccccabccbbbfcccbcbcaabbbbfcccccabccccf.........................
                ....................daccbfcccccabbbbbfccbcbcbcccaccbfcccccacbbccf.........................
                ....................dabbbfcccccabbccbcccbcbcbcccaccbfcccccaccbccf.........................
                ....................dabccfcccccabbbbfcccbcbcbcbccacbfbccccaccbccf.........................
                ....................dabccbbbbbbcccbfccbcbcbcbcbccabbcbbbbbbbbbbcf.........................
                ....................dbbbbbbbbbbccbbfccbcbcbcbcbccabbccccbbbbbbccf.........................
                ....................dabbbbbccbbbbbbfccbcbcbcbcbccabbbbccbbcbbcccf.........................
                ....................dabcbbcccbbbbbfcccbcbcbcbcbcccabbbbbbbccbcccf.........................
                ....................dabccbccbbbbbcfcccbcbcbcbcbcccabbbbcccbccbbcf.........................
                ....................daccbbbbbbbbccfcccbcbcbcbcbcccaccbbbccbbcbbcf.........................
                ....................daccbbbbbcbbcbfcccbcbcbcbcbcccabbbbbbbbbbbbcf.........................
                ....................daccbbbbbcccbbfcccbcbcbcbcbcccabbbcccbbbbcccf.........................
                ....................daccbbccbbccbbfcccbcbcbcbcbcccaccbcccbbcccbcf.........................
                ....................dabbccbbbbbbbbfcccbcbcbcbcbcccaccbbbbbbbbbbcf.........................
                ...................bdabbcbbbbbbbbbfcccbcbcbcbcbcccacbbbbbbbbbbbcf.........................
                .................fcbdcbbbccbcbbbccfcccbcbcbcbcbcccaccbbbcccbbbbcf.ffff....................
                ................cccbbcccbccbccbcccfcccbcbcbcbcbcccacbbbcccbbbbbfffcccffff.................
                .............22cccccccccbbcbbbbbbbfcccbcbcbcbcbcccabbbbbbbbbbbffcccfffffc22...............
                ............cccacc22fff2ccbbbbbbccfcccbcbcbcbcbcccabbbbbbbbbfcaacccfcccbcbb2.22...........
                .......222cccc222222222222ccbbbccbfcccbcbcbcbcbcccabcbbbbbbbbfccaaaac22cccc222c2..........
                ........bccc22a2c2acfcc2222cffbcbfccccbcbcbcbcbcccabcbbbbffcaacccc222222bcbc22a22.........
                .......caaa2222ccccccc22cc22cc222caaaaaaaaaaaaaaabbbcbbaaaffffaaac222222222a22c22c........
                ......cccc2222ccaccbaccca222222c2bcccccccccccccccccbbca22cbcbacacccc2222222abc2cccf.......
                .....c.ccccccccccbbbbccccc22222ccbccccccccccccccccc222222caaaaaaaaccc2222222c22c22........
                ....cc2222222ccccbaccb2cccaca2aaaaaaaaaaaaaabbbbb222c22222bcaaccccccc222222c2222222.......
                ........2222cccccb222222222222bcccccccccccccccb22222c22222ccccccccccc2222222222222c.......
                ..22222222ccc2cbcc2bccc2ac2222bcccccccccccccccb222c2c2ccbcaccaacccccca22222222222222......
                .........22222cbbcccbbb2222aaaaaaaaaaaaaaaabc222c2c2c2ac22ccccacc22222c2caa222222c22222...
                ...2222.c.accccbcbccccc2222bccccccccccccccccc2c222c2c22222bcccccccbcc2c2c2222c2222222222..
                ..222222222222ccccccbc2222cbccccccccccccccccc2c222c22222ccfccbbccccc2222222cc2222222222222
                .....222a.a2c2cbabcbabcbaaaaaaaaaaaaaaccccc222c2c2c222b222bbbcbcb222222222222.............
                ......c.fffffffffffffffffbccccccccccccccccc222222222222ccccccccccccc22c......ccb..........
                .........................bccccccccccccccccc2cc22222cc.222222222222222222..................
                .........................bbbbbbbbbbbbbbbbbbbb.............................................
                ..........................................................................................
                ..........................................................................................
                ..........................................................................................
                ..........................................................................................
                ..........................................................................................
    """))
    adventure.add_to_textlog("press(A) to keep walking.")
    adventure.add_to_textlog("press(B) to run away")
    
    def on_pause_until3():
        pass
    pause_until(on_pause_until3)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you keep walking.")
        pause(500)
        adventure.add_to_textlog("you arrive at the castle.")
        pause(37)
        quest5()
    elif controller.B.is_pressed():
        adventure.add_to_textlog("you run away.")
        pause(11)
        quest6()
def quest1():
    global varrible1
    scene.set_background_image(assets.image("""
        bg0
    """))
    music.play(music.create_song(assets.song("""
            going_on_an_adventure
        """)),
        music.PlaybackMode.IN_BACKGROUND)
    adventure.add_to_textlog("A traveling knight approaches and asks you to join her adventure, and help her remove enemys...")
    pause(1000)
    adventure.change_log_colors(1, 9)
    adventure.add_image_to_text_log(img("""
        ..............c...........................eeeeeee.
                .............cbb.........................e4444444e
                .............ccb.......................eee4ddddd44
                .............cbb.......................e4ee4555554
                .............ccb.....................eee444e44444e
                .............cbb.....................eeeee44eeeee.
                .............ccb...........bccccccccccc1..........
                .............cbb..........bcccccccccccbb1.........
                .............ccb.........bccfffffffffffbb1........
                .............cbb.........ccff11ffff11fffbb........
                .............ccb.........ccff11ffff11fffbb........
                .............cbb.........ccfffffffffffffbb........
                .............ccb.........ccfffffffffffffbb........
                .............cbb.........ccfffffffffffffbb........
                .............ccb.........cccbbbbbbbbbbbcbb........
                .............cbb.........ccccbbbbbbbbccbbb........
                .............ccb.........cccccccccccccbbbb........
                .............cbb.........ccccccccbcbbbbbbb........
                .............ccb.........cccccccccbbbbbbbb........
                .............cbb.........ccccccccbcbbbbbbc........
                .............ccb.........cccccccccbbbbbbbc........
                .............cbb.........ccccccccccbbbbccc888.....
                .............ccb......88ffcccccccbcbbbccc8f188....
                .............cbb.....8cbbffcccccccbbbbcc8fcb1188..
                .............ccb....8bbccbcf8ccbcccbbccffcccbb188.
                .............cbb...8bcbcbcb8ffcccccccc8fccccccb188
                .............ccb...8cbccccc8ffffffffffff88cccccb18
                .............cbb..8bccccc8ffccccbcbcbbcdff8ccccbb8
                ..........ee.ccb.ee8cccc8ffccccccbbbbddbbff8ccccc8
                ...........eeeeeee2ff888ffcccccbcdbddbbbbbf888888.
                ...........222222222ffff8cccbcbcbbbdbbbbbbfffffff.
                ..........22222222222ccf8ccbcbcbcbbbdbbbbb8ffcccb.
                ..........22222222222ccf8cccbcbcbbbdbbbbbb8ffcccb.
                ..........22222222222ccffccccbcbccbbdbbbb8f.fcccb.
                ..........2222222222fff.8f8ffffffffffff88f...cccb.
                ...........222222.2ff.....f8888888888888f....cccb.
                .............eec..........ffffffffffffff.....cccb.
                .............e.c........eeeeeee4eeeeeeeeee...cccb.
                ..............e.........eeeeede4d5d5deeeee...fccb.
                ..............e........eeeee45e45d5d5d4eeee..fccb.
                .......................eeee45de4d5d5d5d4eee..cccb.
                .......................eeeeed5e45d5eed5eeee.2222b.
                .......................eeee45de4d5dee5d4eee.22222c
                .......................eee4de5ee5d5eeded4ee222222c
                .......................e.4.4.4.e.4.e.4.4.e.2.2.2.c
                ........................e...4...4...e...4...2...2.
    """))
    if varrible1 == 0:
        adventure.add_to_textlog("Press (A) to join the fun & easy fighting.")
        adventure.add_to_textlog("Press (B) to turn and run towards the nearby cliff.")
        
        def on_pause_until4():
            pass
        pause_until(on_pause_until4)
        
    elif varrible1 == 1:
        adventure.add_to_textlog("press (A) to continue")
        
        def on_pause_until5():
            pass
        pause_until(on_pause_until5)
        
    if controller.A.is_pressed():
        adventure.add_to_textlog("You start to leave with the knight.")
        adventure.change_score_override(adventure.Currency.COINS, 2)
        adventure.add_image_to_text_log(assets.image("""
            cion
        """))
        adventure.add_to_textlog("You got paid.")
        adventure.change_log_colors(1, 9)
        quest2()
    else:
        adventure.add_to_textlog("it hurt a lot..")
        info.change_life_by(-1)
        scene.set_background_color(2)
        pause(100)
        varrible1 = 1
        quest1()
def questsplit1():
    adventure.add_to_textlog("press (A) to jump off the boat and swim away as fast as you can.")
def quest21():
    adventure.add_to_textlog("Press (A) keep fighting")
    adventure.add_to_textlog("Press (B) to run away")
    
    def on_pause_until6():
        pass
    pause_until(on_pause_until6)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you keep fighting...")
        adventure.add_image_to_text_log(assets.image("""
            land octopuss
        """))
        adventure.add_to_textlog("you were killed by a land octopus.")
        info.change_life_by(-2)
    else:
        adventure.add_to_textlog("you found the traveling knight.")
        quest3()
def quest2():
    music.play(music.create_song(assets.song("""
            a_fairy_and_an_ogre
        """)),
        music.PlaybackMode.IN_BACKGROUND)
    scene.set_background_color(15)
    adventure.add_to_textlog("A warfaring knight approaches and asks you to join his adventure, and help him kill ogres, trolls, orcs, and jotuns...")
    pause(2000)
    adventure.add_image_to_text_log(img("""
        ..............c...........................eeeeeee...............
                .........................................e4444444e..............
                .......................................eee4ddddd44e.............
                .......................................e4ee4555554e.............
                .....................................eee444e44444e..............
                .....................................eeeee44eeeee...............
                ...........................bccccccccccc1........................
                ..........................bcccccccccccbb1.......................
                .........................bccfffffffffffbb1......................
                .........................ccff22ffff22fffbb......................
                .........................ccff22ffff22fffbb......................
                .........................ccfffffffffffffbb......................
                .........................ccfffffffffffffbb......................
                .........................ccfffffffffffffbb......................
                .........................cccbbbbbbbbbbbcbb......................
                .........................ccccbbbbbbbbccbbb......................
                .........................cccccccccccccbbbb......................
                .........................ccccccccbcbbbbbbb......................
                .........................cccccccccbbbbbbbb......................
                .........................ccccccccbcbbbbbbc......................
                .........................cccccccccbbbbbbbc......................
                .........................ccccccccccbbbbccc888...................
                ......................88ffcccccccbcbbbccc8f188..................
                .....................8cbbffcccccccbbbbcc8fcb1188................
                ....................8bbccbcf8ccbcccbbccffcccbb188...............
                ...................8bcbcbcb8ffcccccccc8fccccccb188..............
                ...................8cbccccc8ffffffffffff88cccccb18..............
                ..................8bccccc8ffccccbcbcbbcdff8ccccbb8..............
                ...................8cccc8ffccccccbbbbddbbff8ccccc8..............
                .....................888ffcccccbcdbddbbbbbf888888...............
                ........................8cccbcbcbbbdbbbbbbfffffff...............
                ........................8ccbcbcbcbbbdbbbbb8ffcccb...............
                ........................8cccbcbcbbbdbbbbbb8ffcccb...............
                .........................ccccbcbccbbdbbbb8f.fcccb...............
                ........................8f8ffffffffffff88f...cccb...............
                ..........................f8888888888888f....cccb...............
                ..........................ffffffffffffff.....cccb...............
                ........................eeeeeee4eeeeeeeeee...cccb...............
                ........................eeeeede4d5d5deeeee...fccb...............
                .......................eeeee45e45d5d5d4eeee..fccb...............
                .......................eeee45de4d5d5d5d4eee..cccb...............
                .......................eeeeed5e45d5eed5eeee.ffffb...............
                .......................eeee45de4d5dee5d4eee.fffffc..............
                .......................eee4de5ee5d5eeded4eeffffffc..............
                .......................ee4e4d4eed4dee4d4eeeffffffc..............
                .......................eee4e4eee4d4eee4e4eefffffff..............
                .......................ceeeeeeeee4eeeeeeeecfffffff..............
                .......................ceeeeeeee4e4eeeeeeec.ffffff..............
                .......................cffffffeeeeeeefffffc..ffff...............
                .......................cbccccceeeeeeeccccbc.....................
                .......................bccccccfffffffcccccb.....................
                .......................cbcccccc....ccccccbc.....................
                .......................bccccccc....cccccccb.....................
                .......................cbccccc......cccccbc.....................
                .......................bcccccc......ccccccb.....................
                ......................ffffffff......ffffffff....................
                ......................ffffffff......ffffffff....................
                .......................ffffff........cfffff.....................
                .......................bffffc........cffffb.....................
                .......................cffffc........cffffc.....................
                .......................ffffcc........fcffff.....................
                .......................fffccf........ffcfff.....................
                .......................ffffff........ffffff.....................
                .......................ffffff........ffffff.....................
                .......................ffffff........ffffff.....................
                .......................ffffff........ffffff.....................
                .......................ffffff........ffffff.....................
                .......................ffffff........ffffff.....................
                .......................ffffff........ffffff.....................
                .......................cccccc........fccccc.....................
                .......................cffffc........cffffc.....................
                ......................fcffffcf......fcffffcf....................
                ......................cfffffcc......ccffffcc....................
                .....................ffffffffff....fcffffffcc...................
    """))
    pause(1000)
    adventure.add_to_textlog("Press (A) to join the hard & terrifying fighting.")
    adventure.add_to_textlog("Press (B) to go with the first knight.")
    
    def on_pause_until7():
        pass
    pause_until(on_pause_until7)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you go with him...")
        adventure.add_image_to_text_log(assets.image("""
            goblin
        """))
        adventure.add_to_textlog("You were badly injured...")
        info.change_life_by(-2)
        quest21()
    else:
        adventure.add_to_textlog("you actually leave this time..")
        adventure.add_to_textlog("you start traveling...")
        quest3()
def quest5():
    adventure.add_to_textlog("you enter the castle.")
    adventure.add_to_textlog("guards come and take you somewhere...")
    adventure.add_image_to_text_log(assets.image("""
        gaurd
    """))
    adventure.add_to_textlog("they took you to the throne room...")
    music.play(music.create_song(assets.song("""
            quest_from_the_king
        """)),
        music.PlaybackMode.IN_BACKGROUND)
    adventure.add_image_to_text_log(assets.image("""
        king1
    """))
    adventure.add_to_textlog("you were told by the king to go forth and fetch him a banana or two or three or four or all of them from the market.")
    pause(1000)
    adventure.add_to_textlog("You were catapulted out of the window towards the market.")
    pause(100)
    adventure.add_to_textlog("you landed right in the middle of the market.")
    adventure.add_to_textlog("press (A) to buy some bananas for the king.")
    adventure.add_to_textlog("press (B) to leave without getting bananas for the king.")
    
    def on_pause_until8():
        pass
    pause_until(on_pause_until8)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you got bananas  for the king and then some more over and over again.")
        adventure.set_score_override(adventure.Currency.COINS, 0)
        adventure.add_to_textlog("you got very hungry...")
        info.change_life_by(-1)
        quest7()
    elif controller.B.is_pressed():
        adventure.add_to_textlog("you bought a sword and left.")
        adventure.add_image_to_text_log(assets.image("""
            swordd
        """))
        adventure.set_score_override(adventure.Currency.COINS, 2)
        quest7()
def quest6():
    adventure.add_to_textlog("you see a ship.")
    adventure.add_image_to_text_log(assets.image("""
        ship1
    """))
    adventure.add_to_textlog("press (A) to board the ship.")
    adventure.add_to_textlog("press (B) to sit down and wait forever...")
    
    def on_pause_until9():
        pass
    pause_until(on_pause_until9)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you got on the ship.")
        quest9()
    elif controller.B.is_pressed():
        adventure.add_to_textlog("you sit down & wait forever.")
        game.set_game_over_message(False, "you Died of boredom...")
        game.set_game_over_effect(False, effects.melt)
        game.game_over(False)
def lorestart():
    adventure.add_image_to_text_log(assets.image("""
        dice
    """))
    adventure.add_to_textlog("press (A) to read lore. press (B) to start the game.")
    
    def on_pause_until10():
        pass
    pause_until(on_pause_until10)
    
    if controller.A.is_pressed():
        adventure.add_image_to_text_log(assets.image("""
            scroll of lore
        """))
        pause(100)
        adventure.add_to_textlog("This game is set in medieval times. the character you play as is a warrior without a sword.")
        pause(852)
        adventure.add_to_textlog("In this land there are seven kingdoms consistently battling each other for power. These kingdoms are:")
        pause(3900)
        adventure.add_to_textlog("The seafaring kingdom, ruled by the pirates and Queen Gráinne Mhaol.")
        pause(750)
        adventure.add_to_textlog("The orc kingdom, ruled by the orcs and king Ocrasged.")
        pause(750)
        adventure.add_to_textlog("The troll kingdom, ruled by the trolls and king Grollis.")
        pause(750)
        adventure.add_to_textlog("The dark kingdom, ruled by the dwarfs and king hertrik.")
        pause(750)
        adventure.add_to_textlog("The forest kingdom, ruled by mushroom folk and Queen Iðunn.")
        pause(750)
        adventure.add_to_textlog("The war kingdom, ruled by knights and king Jerun.")
        pause(750)
        adventure.add_to_textlog("&")
        adventure.add_to_textlog("The sky kingdom, ruled by birds and queen laxe.")
        pause(1300)
        adventure.add_to_textlog("The war kingdom fights everybody except the sky kingdom and the dark kingdom.")
        pause(1600)
        adventure.add_to_textlog("The sky kingdom mainly stays in the sky and mountains but sometimes invades the land around the mountains.")
        pause(2000)
        adventure.add_to_textlog("The orc kingdom and the Troll kingdom attack anybody they come across.")
        pause(1000)
        adventure.add_to_textlog("The dark kingdom took the safer strategy and gives the kingdoms weapons in turn for land, except for the orc kingdom and troll kingdom, because they have a grudge against them. The dark kingdom mercilessly attacks the orc kingdom and troll kingdom.")
        pause(10000)
        adventure.add_to_textlog("The seafaring kingdom attacks everybody near the coast.")
        pause(1000)
        adventure.add_to_textlog("the forest kingdom attacks orcs, trolls, & goblins that come into their forests.")
        pause(1000)
        adventure.add_to_textlog("your character lives near the sky and forest kingdoms on the dark kingdoms land and on the seafaring kingdoms land")
        pause(1000)
        adventure.add_to_textlog("starting game...")
        pause(100)
        adventure.add_image_to_text_log(assets.image("""
            remove text
        """))
        quest1()
    elif controller.B.is_pressed():
        adventure.add_image_to_text_log(assets.image("""
            remove text
        """))
        adventure.set_score_override(adventure.Currency.COINS, 1)
        info.set_life(3)
        quest1()
def quest7():
    adventure.add_to_textlog("you met back up with wandering knight.")
    pause(100)
    adventure.add_to_textlog("you and the knight were ambushed by a goblin")
    adventure.add_to_textlog("press (A) to fight")
    adventure.add_to_textlog("press (B) to hide")
    adventure.add_to_textlog("Press (arrow key) to run away")
    
    def on_pause_until11():
        pass
    pause_until(on_pause_until11)
    
    if controller.A.is_pressed():
        adventure.add_to_textlog("you decided to fight")
        pause(100)
        info.change_life_by(-1)
        pause(100)
        adventure.add_to_textlog("you killed the goblin.")
    elif controller.B.is_pressed():
        adventure.add_to_textlog("you hid behind the knight.")
        adventure.add_to_textlog("the knight leaves you and kills the goblin.")
    else:
        adventure.add_to_textlog("you ran away...")
        adventure.add_to_textlog("you fell off a cliff onto a pirates boat.")
        adventure.add_image_to_text_log(assets.image("""
            ship1
        """))
        quest9()
def questsplit1b():
    adventure.add_to_textlog("your arms hurt from scrubbing the decks.")
def questsplit2():
    adventure.add_to_textlog("you keep going forward.")

def on_life_zero():
    game.over(False, effects.splatter)
info.on_life_zero(on_life_zero)

varrible1 = 0
adventure.clear_text_log()
varrible1 = 0
lorestart()